<a href="https://colab.research.google.com/github/ccastaneda-boot/etl-data-pipeline/blob/main/notebooks/Corredores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

In [3]:
df = pd.read_csv(url)

In [13]:
df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

EXPLORACIÓN DE DATOS

In [5]:
#Exploración de datos:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [11]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

LIMPIEZA DE DATOS

In [6]:
corredores = df.copy()

In [7]:
#Elimina espacios al inicio y al final en columnas de texto
corredores.columns = corredores.columns.str.strip().str.lower()

In [8]:
#Elimina espacios al inicio y al final de cada dato de las columnas de tipo "object" (string)
for col in corredores.select_dtypes(include='object').columns:
    corredores[col] = corredores[col].astype(str).str.strip()

In [9]:
#Reemplaza espacios o vacios en celdas por pd.NA (valor nulo estándar de pandas)
corredores = corredores.replace(r'^\s*$', pd.NA, regex=True)

In [10]:
corredores = corredores.drop_duplicates()

In [21]:
corredores["nombre"] = corredores["nombre"].str.title()
corredores["zona"] = corredores["zona"].str.title()
corredores["nivel"]= corredores["nivel"].str.title()

map_rating = {
    "junior": "Junior",
    "mid": "Middle",
    "SENIOR": "Senior",
    "elite": "Elite"
}

corredores["nivel"] = corredores["nivel"].str.lower().map(map_rating)
corredores["nivel"] = corredores["nivel"].fillna("No especificado")
corredores["zona"] = corredores["zona"].fillna("No especificado")

In [28]:
corredores.head()

,id_corredor,nombre,zona,nivel,anios_experiencia
0,1,José López Flores,Paracentral,No especificado,4.0
1,2,José Ortiz García,Centro,Junior,0.0
2,3,María Ramírez Cruz,Centro,No especificado,6.0
3,4,Fernanda Rojas Cruz,Nan,No especificado,8.0
4,5,Ana Gómez Rojas,Nan,No especificado,4.0

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [29]:
validos = corredores[
    corredores['nombre'].notna() &
    corredores['zona'].notna() &
    corredores['nivel'].notna()
].copy()

In [30]:
rechazados = corredores[
    corredores['nombre'].isna() |
    corredores['zona'].isna() |
    corredores['nivel'].isna()
].copy()

MOTIVO DE RECHAZO

In [31]:
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['zona']):
        motivos.append("zona_vacio")


    if pd.isna(row['nivel']):
        motivos.append("nivel_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [32]:
validos.to_csv("corredores_curated.csv", index=False)

In [33]:
rechazados.to_csv("corredores_rejects.csv", index=False)

In [34]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_qs2b_user:vt9HawjFLorrA2FFsCn16HfhQrnZh6qi@dpg-d6qu5q3uibrs739hdpa0-a.oregon-postgres.render.com/etl_seguros_qs2b"
engine = create_engine(database_url)
test = pd.read_sql('SELECT 1', engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

Cargar Data a la DB

In [35]:
validos.to_sql(
    'corredores_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'corredores_rejects',
    engine,
    if_exists='append',
    index=False
)

0

Validar Carga

In [38]:
pd.read_sql(
"SELECT * FROM corredores_curated LIMIT 10",
engine
)

,id_corredor,nombre,zona,nivel,anios_experiencia
0,1,José López Flores,Paracentral,No especificado,4.0
1,2,José Ortiz García,Centro,Junior,0.0
2,3,María Ramírez Cruz,Centro,No especificado,6.0
3,4,Fernanda Rojas Cruz,Nan,No especificado,8.0
4,5,Ana Gómez Rojas,Nan,No especificado,4.0
5,6,Sofía Reyes Hernández,Occidente,Elite,3.0
6,7,Pedro Vásquez Torres,Costa,No especificado,1.0
7,8,Paula Ortiz Hernández,Centro,Junior,17.0
8,9,Carlos Torres Vásquez,Paracentral,Junior,2.0
9,10,Juan Cruz Castillo,Occidente,No especificado,7.0