<a href="https://colab.research.google.com/github/ccastaneda-boot/etl-data-pipeline/blob/main/notebooks/Siniestros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv

In [2]:
import pandas as pd

In [1]:
url="https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

In [3]:
df = pd.read_csv(url)

In [4]:
df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

EXPLORACIÓN DE DATOS

In [5]:
#Exploración de datos:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

LIMPIEZA DE DATOS

In [173]:
siniestros = df.copy()

In [184]:
siniestros.head()

   Id_Siniestro  Id_Poliza Fecha_Siniestro Monto_Siniestro     Estado
0             1      17400      2025-10-16         2092.59    Abierto
1             2       2465      2025-08-01        7,076.25    Abierto
2             3      15785      2025-09-19          702.27    Cerrado
3             4      14299      2025-09-27          274.63    Abierto
4             5      12908      2025-12-01        9,377.69  Rechazado

In [182]:
print('Número de valores NaT en la columna Fecha_Siniestro después de la conversión:')
display(siniestros['Fecha_Siniestro'].isna().sum())

print('\nEjemplos de filas donde "fecha_siniestro" es NaT, mostrando la fecha original:')
display(df.loc[siniestros['Fecha_Siniestro'].isna(), ['fecha_siniestro']].head())

Número de valores NaT en la columna Fecha_Siniestro después de la conversión:

np.int64(0)

Ejemplos de filas donde "fecha_siniestro" es NaT, mostrando la fecha original:

Empty DataFrame
Columns: [fecha_siniestro]
Index: []

In [175]:
#Elimina espacios al inicio y al final en columnas de texto
siniestros.columns = siniestros.columns.str.strip().str.title()

In [176]:
#Elimina espacios al inicio y al final de cada dato de las columnas de tipo "object" (string)
for col in siniestros.select_dtypes(include='object').columns:
    siniestros[col] = siniestros[col].astype(str).str.strip()

In [177]:
#Reemplaza espacios o vacios en celdas por pd.NA (valor nulo estándar de pandas)
siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

In [178]:
siniestros['Estado'] = siniestros['Estado'].str.title()

In [180]:
# Intento de analizar todas las fechas con dayfirst=True
siniestros['Fecha_Siniestro'] = pd.to_datetime(siniestros['Fecha_Siniestro'], errors='coerce', dayfirst=True)

# Identificar las filas que siguen siendo NaT
still_nat_mask = siniestros['Fecha_Siniestro'].isna()

# Para esas filas, intentar analizar los valores de cadena originales (del df original) con el formato YYYY/MM/DD,
# luego repito el código para cada probable formato que tenga el campo Fecha_Siniestro (DD/MM/YY, DD-MM-YY,YYYY-MM-DD, etc)
siniestros.loc[still_nat_mask, 'Fecha_Siniestro'] = pd.to_datetime(
    df.loc[still_nat_mask, 'fecha_siniestro'],
    # Uso la columna original de df para el parseo
    format='%Y/%m/%d',
    errors='coerce'
)

still_nat_mask = siniestros['Fecha_Siniestro'].isna()

siniestros.loc[still_nat_mask, 'Fecha_Siniestro'] = pd.to_datetime(
    df.loc[still_nat_mask, 'fecha_siniestro'],
    format='%d/%m/%Y',
    errors='coerce'
)

still_nat_mask = siniestros['Fecha_Siniestro'].isna()

siniestros.loc[still_nat_mask, 'Fecha_Siniestro'] = pd.to_datetime(
    df.loc[still_nat_mask, 'fecha_siniestro'],
    format='%d/%m/%y',
    errors='coerce'
)

still_nat_mask = siniestros['Fecha_Siniestro'].isna()

siniestros.loc[still_nat_mask, 'Fecha_Siniestro'] = pd.to_datetime(
    df.loc[still_nat_mask, 'fecha_siniestro'],
    format='%Y/%m/%d',
    errors='coerce'
)

still_nat_mask = siniestros['Fecha_Siniestro'].isna()

siniestros.loc[still_nat_mask, 'Fecha_Siniestro'] = pd.to_datetime(
    df.loc[still_nat_mask, 'fecha_siniestro'],
    format='%Y-%m-%d',
    errors='coerce'
)

still_nat_mask = siniestros['Fecha_Siniestro'].isna()

siniestros.loc[still_nat_mask, 'Fecha_Siniestro'] = pd.to_datetime(
    df.loc[still_nat_mask, 'fecha_siniestro'],
    format='%m-%d-%y',
    errors='coerce'
)

In [183]:
siniestros = siniestros.drop_duplicates()

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [189]:
siniestros.head()

   Id_Siniestro  Id_Poliza Fecha_Siniestro Monto_Siniestro     Estado
0             1      17400      2025-10-16         2092.59    Abierto
1             2       2465      2025-08-01        7,076.25    Abierto
2             3      15785      2025-09-19          702.27    Cerrado
3             4      14299      2025-09-27          274.63    Abierto
4             5      12908      2025-12-01        9,377.69  Rechazado

In [186]:
validos = siniestros[
    siniestros['Id_Siniestro'].notna() &
    siniestros['Id_Poliza'].notna() &
    siniestros['Fecha_Siniestro'].notna() &
    siniestros['Monto_Siniestro'].notna() &
    siniestros['Estado'].notna()
].copy()

In [187]:
rechazados = siniestros[
    siniestros['Id_Siniestro'].notna() |
    siniestros['Id_Poliza'].notna() |
    siniestros['Fecha_Siniestro'].notna() |
    siniestros['Monto_Siniestro'].notna() |
    siniestros['Estado'].notna()
].copy()

MOTIVO DE RECHAZO

In [188]:
def motivo(row):

    motivos = []

    if pd.isna(row['Id_Siniestro']):
        motivos.append("ID_Siniestro_vacio")

    if pd.isna(row['Id_Poliza']):
        motivos.append("Id_Poliza_vacio")

    if pd.isna(row['Fecha_Siniestro']):
        motivos.append("Fecha_Siniestro_vacio")

    if pd.isna(row['Monto_Siniestro']):
        motivos.append("Monto_Siniestro_vacio")

    if pd.isna(row['Estado']):
        motivos.append("Estado_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [190]:
validos.to_csv("siniestros_curated.csv", index=False)

In [191]:
rechazados.to_csv("siniestros_rejects.csv", index=False)

In [192]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_qs2b_user:vt9HawjFLorrA2FFsCn16HfhQrnZh6qi@dpg-d6qu5q3uibrs739hdpa0-a.oregon-postgres.render.com/etl_seguros_qs2b"
engine = create_engine(database_url)
test = pd.read_sql('SELECT 1', engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

Cargar Data a la DB

In [193]:
validos.to_sql(
    'siniestros_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='append',
    index=False
)

620

Validar Carga

In [199]:
pd.read_sql(
"SELECT * FROM siniestros_curated LIMIT 100",
engine
)

    Id_Siniestro  Id_Poliza Fecha_Siniestro Monto_Siniestro     Estado
0              1      17400      2025-10-16         2092.59    Abierto
1              2       2465      2025-08-01        7,076.25    Abierto
2              3      15785      2025-09-19          702.27    Cerrado
3              4      14299      2025-09-27          274.63    Abierto
4              5      12908      2025-12-01        9,377.69  Rechazado
..           ...        ...             ...             ...        ...
95            96      17713      2026-02-21        7,797.66    Abierto
96            97      13086      2025-01-01               -  Rechazado
97            98      19925      2025-01-25        1.228,19        Nan
98            99      18399      2025-06-27        2.077,75    Cerrado
99           100      24052      2025-03-16        2.342,67        Nan

[100 rows x 5 columns]