<a href="https://colab.research.google.com/github/ccastaneda-boot/etl-data-pipeline/blob/main/notebooks/Tipos_seguro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv

In [2]:
import pandas as pd

In [3]:
url="https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"

In [4]:
df = pd.read_csv(url)

In [7]:
df.head(50)

    id_tipo_seguro        tipo     categoria riesgo_base
0                1        Pyme      Familiar           -
1                2  Industrial   Empresarial       4.68
2                3  Industrial      Familiar        5.10
3                4  Industrial      Personal         NaN
4                5        Auto  empresarial         9.07
5                6  Industrial   Empresarial        2.52
6                7       Salud      Personal       0.92
7                8   Educación  empresarial        7.42
8                9  Accidentes           NaN       5.68
9               10      Dental      Especial        2.70
10              11        Auto  empresarial         4.33
11              12    Agrícola           NaN         NaN

EXPLORACIÓN DE DATOS

In [8]:
#Exploración de datos:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

LIMPIEZA DE DATOS

In [9]:
tipos_seguros = df.copy()

In [10]:
#Elimina espacios al inicio y al final en columnas de texto
tipos_seguros.columns = tipos_seguros.columns.str.strip().str.lower()

In [11]:
#Elimina espacios al inicio y al final de cada dato de las columnas de tipo "object" (string)
for col in tipos_seguros.select_dtypes(include='object').columns:
    tipos_seguros[col] = tipos_seguros[col].astype(str).str.strip()

In [12]:
#Reemplaza espacios o vacios en celdas por pd.NA (valor nulo estándar de pandas)
tipos_seguros = tipos_seguros.replace(r'^\s*$', pd.NA, regex=True)

In [13]:
tipos_seguros['tipo'] = tipos_seguros['tipo'].str.title()

In [14]:
tipos_seguros['categoria'] = tipos_seguros['categoria'].str.title()

In [15]:
tipos_seguros = tipos_seguros.drop_duplicates()

In [18]:
tipos_seguros.head()

   id_tipo_seguro        tipo    categoria riesgo_base
0               1        Pyme     Familiar           -
1               2  Industrial  Empresarial        4.68
2               3  Industrial     Familiar        5.10
3               4  Industrial     Personal         nan
4               5        Auto  Empresarial        9.07

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [19]:
validos = tipos_seguros[
    tipos_seguros['tipo'].notna() &
    tipos_seguros['categoria'].notna()
].copy()

In [20]:
rechazados = tipos_seguros[
    tipos_seguros['tipo'].isna() |
    tipos_seguros['categoria'].isna()
].copy()

MOTIVO DE RECHAZO

In [21]:
def motivo(row):

    motivos = []

    if pd.isna(row['tipo']):
        motivos.append("tipo_vacio")

    if pd.isna(row['categoria']):
        motivos.append("categoria_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [22]:
validos.to_csv("tipos_seguros_curated.csv", index=False)

In [23]:
rechazados.to_csv("tipos_seguros_rejects.csv", index=False)

In [24]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_qs2b_user:vt9HawjFLorrA2FFsCn16HfhQrnZh6qi@dpg-d6qu5q3uibrs739hdpa0-a.oregon-postgres.render.com/etl_seguros_qs2b"
engine = create_engine(database_url)
test = pd.read_sql('SELECT 1', engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 55.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

Cargar Data a la DB

In [25]:
validos.to_sql(
    'tipos_seguros_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'tipos_seguros_rejects',
    engine,
    if_exists='append',
    index=False
)

0

Validar Carga

In [28]:
pd.read_sql(
"SELECT * FROM tipos_seguros_curated LIMIT 10",
engine
)

   id_tipo_seguro        tipo    categoria riesgo_base
0               1        Pyme     Familiar           -
1               2  Industrial  Empresarial        4.68
2               3  Industrial     Familiar        5.10
3               4  Industrial     Personal         nan
4               5        Auto  Empresarial        9.07
5               6  Industrial  Empresarial        2.52
6               7       Salud     Personal        0.92
7               8   Educación  Empresarial        7.42
8               9  Accidentes          Nan        5.68
9              10      Dental     Especial        2.70